apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ntby
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-ntby@sha256:42bf4c6fdd2a59f98eaff3e8599afa5ba9b702145fb36d24c39d513440f90ada
        name: my-nodejs
        resources: {}
status: {}
